Exit actions when version is missing

diff --git a/helpers/verify-version/action.yml b/helpers/verify-version/action.yml
--- a/helpers/verify-version/action.yml
+++ b/helpers/verify-version/action.yml
@@ -23,6 +23,11 @@ runs:
         setup_version="$(python3 $ACTION_PATH/../read_version.py)"
         branch_version=$(echo "$REF" | awk -F"/" '{print $NF}' )
 
+        if [[ "${branch_version}" === "" ]]; then
+          echo "::error::Verson is empty"
+          exit 1
+        fi
+
         if [[ "$INPUTS_IGNORE_DEV" =~ true|True ]] && [ "${branch_version}" == "dev" ]; then
           exit 0
         elif [[ "$INPUTS_IGNORE_MASTER" =~ true|True ]] && [ "${branch_version}" == "master" ]; then
diff --git a/helpers/version/action.yml b/helpers/version/action.yml
--- a/helpers/version/action.yml
+++ b/helpers/version/action.yml
@@ -41,6 +41,11 @@ runs:
       run: |
         version=$(echo "$REF" | awk -F"/" '{print $NF}' )
 
+        if [[ "${version}" === "" ]]; then
+          echo "::error::Verson is empty"
+          exit 1
+        fi
+
         if [[ ! -z "$GITHUB_EVENT_INPUTS_VERSION" ]]; then
           version="$GITHUB_EVENT_INPUTS_VERSION"
 
